Repository palantir/sls-packaging, pull requests merged in 2019-10, with the labels that each got.

#641 Create .changelog.yml
  .changelog.yml
Labels: merge when ready, no changelog

#644 Automatically detect mainClass
  changelog/@unreleased/pr-644.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/tasks/LazyCreateStartScriptTask.java
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/util/MainClassResolver.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/ServiceDistributionPluginTests.groovy
Labels: autorelease, merge when ready

#647 Correctly configure run task
  changelog/@unreleased/pr-647.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/ServiceDistributionPluginTests.groovy
Labels: autorelease, merge when ready

#649 Actually configure run task correctly
  changelog/@unreleased/pr-649.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
Labels: autorelease

#652 Demonstrate main class inference failure
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/MainClassInferenceIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/ServiceDistributionPluginTests.groovy
  readme.md
Labels: merge when ready, no changelog
