Repository palantir/sls-packaging, pull requests merged in 2019-12, with the labels that each got.

#702 Mention $projectVersion in README
  readme.md
Labels: merge when ready, no changelog

#711 Stop using VERSION_HIGHER instead of 13
  changelog/@unreleased/pr-711.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/gc/GcProfile.java
Labels: autorelease, merge when ready

#710 Fix: typo in UseNUMA option in response-time gc config leads to unrecognized vm option error
  changelog/@unreleased/pr-710.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/gc/GcProfile.java
Labels: merge when ready

#715 upgrade yourkit
  changelog/@unreleased/pr-715.v2.yml
  gradle-sls-packaging/build.gradle
Labels: autorelease, merge when ready
