Repository palantir/sls-packaging, pull requests merged in 2020-03, with the labels that each got.

#844 Handle multiple in repo recommended pdeps sources
  changelog/@unreleased/pr-844.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestTaskIntegrationSpec.groovy
Labels: autorelease, merge when ready

#846 Log raw product dependency before validating
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java
Labels: autorelease, merge when ready, no changelog

#849 Time to deal with these deprecations
  gradle-recommended-product-dependencies/src/test/groovy/com/palantir/gradle/dist/RecommendedProductDependenciesPluginIntegrationSpec.groovy
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/asset/AssetDistributionPlugin.java
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/DistTarTask.java
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/tasks/DistTarTask.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/GradleIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/asset/AssetDistributionPluginIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/GcProfileIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPluginTests.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/MainClassInferenceIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/tasks/CopyYourkitAgentTaskIntegrationSpec.groovy
Labels: autorelease, merge when ready, no changelog

#852 Fix regression: no longer require gradle 6
  changelog/@unreleased/pr-852.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/SlsBaseDistPlugin.java
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/DistTarTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/GradleIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPluginTests.groovy
Labels: autorelease, merge when ready

#853 Apply rev-api to gradle-recommended-product-dependencies
  build.gradle
  gradle-recommended-product-dependencies/build.gradle
Labels: merge when ready, no changelog
