Repository palantir/sls-packaging, pull requests merged in 2020-06, with the labels that each got.

#912 Fix: Upgrade yourkit to b139 to fix broken develop
  gradle-sls-packaging/build.gradle
Labels: merge when ready, no changelog

#913 Fix typo in Java 14 flags
  changelog/@unreleased/pr-913.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/tasks/LaunchConfigTask.java
Labels: autorelease, merge when ready

#916 Expose product dependency list property
  changelog/@unreleased/pr-916.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/BaseDistributionExtension.java
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/BaseDistributionExtensionTest.groovy
Labels: autorelease, merge when ready

#919 Tolerate multiple declared dependencies
  changelog/@unreleased/pr-919.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/tasks/CreateManifestTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestTaskIntegrationSpec.groovy
Labels: autorelease, merge when ready

#925 go-java-launcher 1.9.0 -> 1.9.1
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
Labels: autorelease, merge when ready, no changelog

#926 Properly configure shenandoah
  changelog/@unreleased/pr-926.v2.yml
  gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/gc/GcProfile.java
Labels: autorelease, merge when ready

#946 Upgrade yourkit
  gradle-sls-packaging/build.gradle
Labels: merge when ready, no changelog
