Repository palantir/sls-packaging, pull requests merged in 2021-06, with the labels that each got.

#1151 Add javaVersion docs
  changelog/@unreleased/pr-1151.v2.yml
  readme.md
Labels: merge when ready

#1150 resolve race condition with jar manifest manipulation
  changelog/@unreleased/pr-1150.v2.yml
  gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/RecommendedProductDependencies.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/tasks/ResolveProductDependenciesTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/ResolveProductDependenciesTaskIntegrationSpec.groovy
Labels: merge when ready

#1154 Revert "resolve race condition with jar manifest manipulation (#1150)"
  .palantir/revapi.yml
  changelog/@unreleased/pr-1154.v2.yml
  gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/RecommendedProductDependencies.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/tasks/ResolveProductDependenciesTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/ResolveProductDependenciesTaskIntegrationSpec.groovy
Labels: autorelease, merge when ready

#1160 Disable biased locking
  changelog/@unreleased/pr-1160.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/tasks/LaunchConfigTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPluginTests.groovy
Labels: autorelease, merge when ready

#1164 Feature: Discover product dependencies in a lazy, pluggable way
  changelog/@unreleased/pr-1164.v2.yml
  gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/CompileRecommendedProductDependencies.java
  gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/RecommendedProductDependencies.java
  gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/RecommendedProductDependenciesPlugin.java
  gradle-recommended-product-dependencies/src/test/groovy/com/palantir/gradle/dist/RecommendedProductDependenciesExtensionTest.groovy
  gradle-recommended-product-dependencies/src/test/groovy/com/palantir/gradle/dist/RecommendedProductDependenciesPluginIntegrationSpec.groovy
  gradle-sls-packaging/build.gradle
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/ObjectMappers.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/ProductDependencyIntrospectionPlugin.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/ProductDependencyLockFile.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/ProductId.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/DependencyDiscovery.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/ExtractFileFromJar.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/ExtractSingleFileOrManifest.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/FileAndManifestExtractParameter.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/FileExtractParameter.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/PreferProjectCompatibilityRule.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/SelectSingleFile.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/pdeps/ProductDependencies.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/pdeps/ProductDependencyManifest.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/pdeps/ResolveProductDependenciesTask.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/Diagnostics.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/DiagnosticsManifestPlugin.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/MergeDiagnosticsJsonTask.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/tasks/ConfigTarTask.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/tasks/CreateManifestTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/pdeps/ResolveProductDependenciesIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/pdeps/ResolveProductDependenciesTaskSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestTaskIntegrationSpec.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestTaskTest.groovy
  versions.lock
Labels: autorelease, merge when ready

#1166 Handle missing manifest when transforming artifacts
  changelog/@unreleased/pr-1166.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/artifacts/ExtractSingleFileOrManifest.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/pdeps/ResolveProductDependenciesIntegrationSpec.groovy
  gradle-sls-packaging/src/test/resources/missing-manifest.jar
Labels: autorelease

#1167 fix check for duplicated product dependencies
  changelog/@unreleased/pr-1167.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/pdeps/ResolveProductDependenciesTask.java
Labels: autorelease, merge when ready

#1168 Update version badge
  readme.md
Labels: merge when ready, no changelog

#1149 Bump go-java-launcher version.
  changelog/@unreleased/pr-1149.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
Labels: autorelease, merge when ready
