Repository palantir/sls-packaging, pull requests merged in 2021-02, with the labels that each got.

#1074 Add support for optional dependencies
  .palantir/revapi.yml
  changelog/@unreleased/pr-1074.v2.yml
  gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/ProductDependency.java
  gradle-recommended-product-dependencies/src/main/java/com/palantir/gradle/dist/RecommendedProductDependenciesExtension.java
  gradle-recommended-product-dependencies/src/test/groovy/com/palantir/gradle/dist/RecommendedProductDependenciesPluginIntegrationSpec.groovy
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/BaseDistributionExtension.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/ProductDependencyLockFile.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/tasks/CreateManifestTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/ProductDependencyLockFileTest.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestTaskIntegrationSpec.groovy
Labels: merge when ready

#1076 Added optional dependencies to README
  readme.md
Labels: merge when ready, no changelog

#1078 correctly merge optional and non-optional dependencies
  changelog/@unreleased/pr-1078.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/ProductDependencyMerger.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/tasks/CreateManifestTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/ProductDependencyMergerTest.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestTaskIntegrationSpec.groovy
Labels: autorelease, merge when ready

#1081 Update YourKit to 2020.9-b424 from 2020.9-b416
  changelog/@unreleased/pr-1081.v2.yml
  gradle-sls-packaging/build.gradle
Labels: merge when ready

#1080 JavaServiceDistributionPlugin supports configuring java agents
  changelog/@unreleased/pr-1080.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/DistTarTask.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/tasks/LaunchConfigTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPluginTests.groovy
Labels: autorelease, merge when ready

#1084 The new `javaAgent` configuration is no longer non-transitive
  changelog/@unreleased/pr-1084.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/tasks/LaunchConfigTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPluginTests.groovy
Labels: autorelease, merge when ready

#1085 Allow more lenient minimum version compares for intra-module product …
  changelog/@unreleased/pr-1085.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/ProductDependencyLockFile.java
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/tasks/CreateManifestTask.java
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/ProductDependencyLockFileTest.groovy
  gradle-sls-packaging/src/test/groovy/com/palantir/gradle/dist/tasks/CreateManifestTaskIntegrationSpec.groovy
Labels: autorelease, merge when ready

#1086 bump go-java-launcher to 1.11.0 (was 1.10.0)
  changelog/@unreleased/pr-1086.v2.yml
  gradle-sls-packaging/src/main/java/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.java
Labels: autorelease, merge when ready
